name: Node.js CI

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:

  test-node:

    name: Tests

    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12.x, 13.x ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run tests
        run: npm run test
