name: Publish

on:
  release:
    types: [prereleased]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: GITHUB_TOKEN=$GITHUB_TOKEN  node scripts/update-version.js
      - uses: EndBug/add-and-commit@v8.0.2
        with:
          commit: --signoff
          default_author: user_info
          message: 'Updating version'
          pathspec_error_handling: ignore
      - run: npm publish
      - run: GITHUB_TOKEN=$GITHUB_TOKEN  node scripts/create-release.js